language: generic

os: linux
dist: xenial

env:
  global:
    - PATH=${PATH}:${TRAVIS_BUILD_DIR}/assets
    - VERSION="0.11.11"

addons:
  apt:
    packages:
      - make

before_install:
  # download terraform binary
  - mkdir -p ${TRAVIS_BUILD_DIR}/assets
  - curl https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip -o ${TRAVIS_BUILD_DIR}/assets/terraform.zip
  - unzip ${TRAVIS_BUILD_DIR}/assets/terraform.zip -d ${TRAVIS_BUILD_DIR}/assets
  - rm -f ${TRAVIS_BUILD_DIR}/assets/terraform.zip && chmod +x ${TRAVIS_BUILD_DIR}/assets/terraform

before_script:
  # decrypt encrypted GCP auth file
  - openssl aes-256-cbc -md sha256 -salt -a -d -in ${TRAVIS_BUILD_DIR}/terraform/gcp/${GCP_ENCRYPTED_AUTH_FILE} -out ${TRAVIS_BUILD_DIR}/terraform/gcp/${GCP_DECRYPTED_AUTH_FILE} -pass env:ENCRYPTION_PWD

script:
  - make test